### ISSUE TITLE
idno changes for p.giss

### ISSUE THREAD

**Issue by jcowey** [papyri/idp.data#156]
P.Giss. II has just been published (2020).
What was known as P.Giss. has to become P.Giss. I. 

This means that a global change of all idnos of the type `p.giss;;(\d+)` has to be changed to `p.giss;1;$1`.
and
`p.giss.(\d+)` has to be changed to `p.giss.1.$1`.

This will have to be done across idp.data/DDB_EpiDoc_XML and idp.data/HGV_meta_EpiDoc

**Comment by jcowey** [comment]
These should now be fine. Will close once the next re-index is done and they can be checked one final time.

**Comment by samosafuz** [comment]
This now looks ok to me @jcowey, but #214 does not seem to have indexed properly: the display when browsing the DDB [p.bas](https://papyri.info/browse/ddbdp/p.bas) page shows the files from p.bas;1 scattered loosely instead of gathered in a `p.bas;1` folder, and each of those files redirects to an empty volume `https://papyri.info/search?&COLLECTION=ddbdp&SERIES=p.bas&VOLUME=`. The idnos in each file, however, are correct.

**Comment by samosafuz** [comment]
This looks to be indexed properly now.
