### ISSUE TITLE
proximity search error

### ISSUE THREAD

**Issue by wgclaytor** [papyri/idp.data#287]
I've been having trouble with proximity searches for a while, often finding that any search over around 12-15 characters runs into an error. Here's an example: https://papyri.info/search?STRING=(%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%B1%CF%84%CE%B5%CE%B9+NEAR+%CF%83%CF%84%CF%81%CE%B1%CF%84%CE%B7%CE%B3%CF%89)~20chars&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15

**Comment by hcayless** [comment]
This is an unfortunate limitation of the search engine software we use (it prevents you from creating a search that would bog down the server and ultimately cause it to fail), but you should be able to work around it by choosing 'words' rather than 'characters' as the distance metric, e.g. https://papyri.info/search?STRING=(%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%B1%CF%84%CE%B5%CE%B9+NEAR+%CF%83%CF%84%CF%81%CE%B1%CF%84%CE%B7%CE%B3%CF%89)~5words&no_caps=on&no_marks=on&target=text&DATE_MODE=LOOSE&DOCS_PER_PAGE=15 (γραμματει NEAR στρατηγω within 5 words).
