### ISSUE TITLE
Explanation for provenance types

### ISSUE THREAD

**Issue by Xennis** [papyri/idp.data#439]
Hi! For the `provenance` field this repo contains the following types (`type` attribute):

```
acquired
composed
executed
found
located
received
sent
stored
written
```

Can I find somewhere a documentation what each type means?

## Example

Example of the field I'm talking about, here with the types `found` and `composed`

https://github.com/papyri/idp.data/blob/c258522d8ae0956fdf22bd4602f3cc9771f24b6f/DCLP/69/68001.xml#L45-L58

**Comment by samosafuz** [comment]
These different values for `provenance[@type]` are descriptive, but there is considerable room for overlap: something that was `stored` somewhere was probably also `found` there; something that was `composed` in one place was probably also `sent` from there. In the `DCLP` collection, one finds `found` and `written` consistently, because this collection is built upon metadata in the [Leuven Database of Ancient Books](https://www.trismegistos.org/LDAB); in the `HGV` collection, `located` is the most common `@type`. There is no documentation or schema that governs these, but for discussion of place, see the discussion of [Trismegistos](https://www.trismegistos.org/geo/about.php).

**Comment by Xennis** [comment]
Thanks a lot for the clarification.
