### ISSUE TITLE
Messy stuff again

### ISSUE THREAD

**Issue by jcowey** [papyri/idp.data#82]
Please look at http://papyri.info/editor/publications/70049/ddb_identifiers/158476/edit

sitting in the Finalize section and apparently not renamed.

O.Trim. 2, 516 (Federica Nicolardi)    SoSOL 2018 575   O.Trim. 2, 516

But see
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.trim/o.trim.2/o.trim.2.516.xml
 so it was renamed and was finalized.
See
http://papyri.info/search?DATE_MODE=LOOSE&VOLUME=2&IDNO=516&DOCS_PER_PAGE=15&SERIES=O.Trim.
And
http://papyri.info/ddbdp/o.trim;2;516
The finalization process took many, many minutes. First of all the text jumped down to the approved section. I signed out. When I signed back in again it appeared in the Finalize section.

If you look at the commits from 2 December 2018
https://github.com/papyri/idp.data/commit/b2278b6a69d385c12d5160559606e0d25ae06397
https://github.com/papyri/idp.data/commit/cdeb0b168fc1f8dc95844f1b9bb3de902d03b988
https://github.com/papyri/idp.data/commit/0469cdc77d149ade6b8dec3c5f705bda1728e8e7

all look strange. 

http://papyri.info/editor/users/thokru
http://papyri.info/editor/users/Korshi
http://papyri.info/editor/users/Na%C3%AFm%20Vanthieghem
 did NOT finalize anything that day (2 December 2018).

https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/sosol/sosol.2018

also looks strange. 

I append at list of the commits from the time that things appear to have started acting strangely.
[finalization2dec18.pdf](https://github.com/papyri/idp.data/files/2641290/finalization2dec18.pdf)

Furthermore I have two texts which are awaiting an extra vote even though I voted them straight through to finalization. 

Please can you check, Hugh, whether my repo really is clean. Has it become clogged again. That incipient trouble has maybe broken out.

**Comment by ryanfb** [comment]
These both look like cases where the MySQL state simply doesn't reflect the Git state. So for example, the identifier rename succeeded in Git but was rolled back at some point in MySQL, and a MySQL "Lock wait timeout" prevented changing the MySQL status of the publication to "committed" even though Git finalization succeeded (see attached backtrace: [messystuff82.txt](https://github.com/papyri/idp.data/files/2644348/messystuff82.txt)).

So I don't think there's a huge issue, just a publication that's now in an inconsistent state in the editor. I'm going to restart the editor and MySQL server, since I see a number of "Lock wait timeouts" since the last restart. Possibly there's something we need to look into (again) in the code to see if we can try to mitigate this issue cropping up in the first place.

**Comment by ryanfb** [comment]
Manually reset the main publication involved to the correct renamed/finalized state.
